#!/bin/bash

ARCH=$1
INSTALL=$2

build_msgpack() {
    local path="$1"
    local dest="$2"
    if [ -f Makefile ]; then
        make clean
    fi
    PATH="$path" ruby extconf.rb \
        make clean && \
        make && \
        strip ./msgpack.so && \
        mkdir -p $dest && \
        cp -p ./msgpack.so $dest/msgpack.so
}

pushd /tmp
    if [ ! -d $INSTALL ]; then
        mkdir -p $INSTALL
    fi
    curl -ksOL https://github.com/msgpack/msgpack-ruby/archive/v0.5.9.zip
    unzip -q v0.5.9.zip
    pushd msgpack-ruby-0.5.9/ext/msgpack
        build_msgpack "/ruby-1.8/bin:$PATH" "${INSTALL}/1.8/${ARCH}"
        build_msgpack "/ruby-1.9/bin:$PATH" "${INSTALL}/1.9/${ARCH}"
        build_msgpack "/ruby-2.0/bin:$PATH" "${INSTALL}/2.0/${ARCH}"
        build_msgpack "/ruby-2.1/bin:$PATH" "${INSTALL}/2.1/${ARCH}"
    popd
popd

