#!/bin/sh

# 1.8.7-p374
cd /tmp
curl -sL -o ruby-1.8.7-p374.tar.gz http://cache.ruby-lang.org/pub/ruby/1.8/ruby-1.8.7-p374.tar.gz
tar zxf ruby-1.8.7-p374.tar.gz 
cd ruby-1.8.7-p374
./configure --prefix=/ruby-1.8 --enable-static && make && make install

# 1.9.3-p547
cd /tmp
curl -sL -o ruby-1.9.3-p547.tar.gz http://cache.ruby-lang.org/pub/ruby/1.9/ruby-1.9.3-p547.tar.gz
tar zxf ruby-1.9.3-p547.tar.gz
cd ruby-1.9.3-p547
./configure --prefix=/ruby-1.9 --disable-install-rdoc && make && make install

# 2.0.0-p576
cd /tmp
curl -sL -o ruby-2.0.0-p576.tar.gz http://cache.ruby-lang.org/pub/ruby/2.0/ruby-2.0.0-p576.tar.gz
tar zxf ruby-2.0.0-p576.tar.gz 
cd ruby-2.0.0-p576
./configure --prefix=/ruby-2.0 --disable-install-rdoc && make && make install

# 2.1.3
cd /tmp
curl -sL -o ruby-2.1.3.tar.gz http://cache.ruby-lang.org/pub/ruby/2.1/ruby-2.1.3.tar.gz
tar zxf ruby-2.1.3.tar.gz
cd ruby-2.1.3
./configure --prefix=/ruby-2.1 --disable-install-rdoc && make && make install

