#!/bin/sh

BASE=/root/linux

cp -fp $PWD/build* i386/
fdocker build -t sqlite3-ruby:i386 i386/

cp -fp $PWD/build* x86_64/
docker build -t sqlite3-ruby:x86_64 x86_64/

mkdir -p $BASE
chcon -Rt svirt_sandbox_file_t $BASE

mkdir -p $BASE/sqlite
docker run -v $BASE/sqlite:/build:rw sqlite3-ruby:i386   /build_sqlite3-ruby i386   /build
docker run -v $BASE/sqlite:/build:rw sqlite3-ruby:x86_64 /build_sqlite3-ruby x86_64 /build

mkdir -p $BASE/msgpack
docker run -v $BASE/msgpack:/build:rw sqlite3-ruby:i386   /build_msgpack-ruby i386   /build
docker run -v $BASE/msgpack:/build:rw sqlite3-ruby:x86_64 /build_msgpack-ruby x86_64 /build

