#!/bin/sh

# RUN yum -y install make curl unzip gcc openssl openssl-devel subversion bison zlib zlib-devel

# autoconf 2.60 for 1.8.7-p375 build 
pushd /tmp
curl -sOL http://ftp.gnu.org/gnu/autoconf/autoconf-2.60.tar.gz
tar zxf autoconf-2.60.tar.gz
pushd autoconf-2.60
    ./configure && make && make install
popd
hash -r

# 1.8.7-p375
svn co -q -r 44351 http://svn.ruby-lang.org/repos/ruby/branches/ruby_1_8_7 ruby_1_8_7
pushd ruby_1_8_7
    autoconf
    ./configure --prefix=/ruby-1.8 --enable-static && make && make install
popd

# 1.9.3-p547
curl -sL -o ruby-1.9.3-p547.tar.gz http://cache.ruby-lang.org/pub/ruby/1.9/ruby-1.9.3-p547.tar.gz
tar zxf ruby-1.9.3-p547.tar.gz
pushd ruby-1.9.3-p547
    ./configure --prefix=/ruby-1.9 --disable-install-rdoc && make && make install
popd

# 2.0.0-p481
curl -sL -o ruby-2.0.0-p576.tar.gz http://cache.ruby-lang.org/pub/ruby/2.0/ruby-2.0.0-p576.tar.gz
tar zxf ruby-2.0.0-p481.tar.gz 
pushd ruby-2.0.0-p481
    ./configure --prefix=/ruby-2.0 --disable-install-rdoc && make && make install
popd

# 2.1.3
curl -sL -o ruby-2.1.3.tar.gz http://cache.ruby-lang.org/pub/ruby/2.1/ruby-2.1.3.tar.gz
tar zxf ruby-2.1.3.tar.gz
pushd ruby-2.1.3
    ./configure --prefix=/ruby-2.1 --disable-install-rdoc && make && make install
popd
