#!/bin/bash

ARCH=$1
INSTALL=$2

mingw_rakefile() {
    local rbver="$1"
    local extarch=""
    local rakebin=""

    if [ $ARCH = "i386-mingw32" -o $ARCH = "x64-mingw32" ]; then
        extarch=$ARCH
    fi

    if [ $ARCH = "i386-mingw32" ]; then
        rakebin=i686-w64-mingw32/ruby-$rbver*
    elif [ $ARCH = "x64-mingw32" ]; then
        rakebin=x86_64-w64-mingw32/ruby-$rbver*
    fi

    # Exist check 
    if [ ! -d $HOME/.rake-compiler/builds/$rakebin ]; then
      return 1
    fi

    cat << _EOT_ > Rakefile
# coding: utf-8

require "rake/extensiontask"

Rake::ExtensionTask.new do |e|
  e.cross_compile = true
  e.cross_platform = "$extarch"
  e.name = "msgpack"
  e.ext_dir = "./"
  e.lib_dir = "./"
  e.tmp_dir = "./"
end
_EOT_
  return 0
}

build_msgpack() {
    local path="$1"
    local dest="$2"
    local gccstrip="strip"
    local rbver=`PATH="$path" ruby -e 'puts RUBY_VERSION'`

    # MinGW envirnoment (use rake-compiler gem)
    if [ $ARCH = "i386-mingw32" ]; then
        # x86 (win32)
        gccstrip="i686-w64-mingw32-strip"
    elif [ $ARCH = "x86-mingw32" ]; then
        # x86_64 (win32)
        gccstrip="x86_64-w64-mingw32-strip"
    fi
    if [ -f Makefile ]; then
        make clean
    fi

    if [ $ARCH = "i386-mingw32" -o $ARCH = "x64-mingw32" ]; then
        mingw_rakefile $rbver
        if [ $? -ne 0 ]; then
            echo Skip compile: $ARCH $rbver
            return 1
        fi
        PATH="$path" rake cross clean && \
            LDFLAGS="-static-libgcc" PATH="$path" rake cross compile
    else
        PATH="$path" ruby extconf.rb \
            make clean && \
            make
    fi

    $gccstrip ./msgpack.so && \
        mkdir -p $dest && \
        cp -p ./msgpack.so $dest/msgpack.so
}

pushd /tmp
    if [ ! -d $INSTALL ]; then
        mkdir -p $INSTALL
    fi
    curl -ksOL https://github.com/msgpack/msgpack-ruby/archive/v0.5.9.zip
    unzip -q v0.5.9.zip
    pushd msgpack-ruby-0.5.9/ext/msgpack
        #build_msgpack "/ruby-1.8/bin:$PATH" "${INSTALL}/1.8/${ARCH}"
        #build_msgpack "/ruby-1.9/bin:$PATH" "${INSTALL}/1.9/${ARCH}"
        build_msgpack "/ruby-2.0/bin:$PATH" "${INSTALL}/2.0/${ARCH}"
        #build_msgpack "/ruby-2.1/bin:$PATH" "${INSTALL}/2.1/${ARCH}"
    popd
popd

